version: '3.1'
services:
  express-db:
    image: postgres:13
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5454:5432

volumes:
  postgres_database: